# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(blank=True, max_length=100, null=True)),
                ('card1', models.IntegerField(default=-1, null=True)),
                ('card2', models.IntegerField(default=-1, null=True)),
                ('card3', models.IntegerField(default=-1, null=True)),
                ('card4', models.IntegerField(default=-1, null=True)),
                ('p1cards', models.CharField(blank=True, max_length=150, null=True)),
                ('p2cards', models.CharField(blank=True, max_length=150, null=True)),
                ('p3cards', models.CharField(blank=True, max_length=150, null=True)),
                ('p4cards', models.CharField(blank=True, max_length=150, null=True)),
                ('team1score', models.IntegerField(default=0, null=True)),
                ('team2score', models.IntegerField(default=0, null=True)),
                ('endIndex', models.IntegerField(default=1, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('phase', models.IntegerField(default=0, null=True)),
                ('trump', models.IntegerField(default=1, null=True)),
                ('trumpSuite', models.IntegerField(default=1, null=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_pos', to='piece.Player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_pos', to='piece.Player')),
                ('player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_pos', to='piece.Player')),
                ('player4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_pos', to='piece.Player')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piece.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piece.Player'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piece.Player'),
        ),
    ]
